// lib/categories.ts
// Fichier partagé — importer dans page.tsx et publier/page.tsx

export const SUBCATEGORIES: Record<string, { value: string; label: string }[]> = {
  voiture: [
    { value: '', label: 'Toutes les voitures' },
    { value: 'berline', label: 'Berline' },
    { value: 'suv', label: 'SUV / 4x4' },
    { value: 'pickup', label: 'Pick-up' },
    { value: 'minibus', label: 'Minibus / Van' },
    { value: 'camion', label: 'Camion' },
    { value: 'utilitaire', label: 'Utilitaire' },
    { value: 'autre', label: 'Autre' },
  ],
  moto: [
    { value: '', label: 'Toutes les motos' },
    { value: 'moto', label: 'Moto' },
    { value: 'scooter', label: 'Scooter' },
    { value: 'velo-electrique', label: 'Vélo électrique' },
    { value: 'tricycle', label: 'Tricycle' },
    { value: 'autre', label: 'Autre' },
  ],
  electronique: [
    { value: '', label: 'Tout l\'électronique' },
    { value: 'telephone', label: 'Téléphone' },
    { value: 'ordinateur', label: 'Ordinateur / Laptop' },
    { value: 'tablette', label: 'Tablette' },
    { value: 'tv', label: 'TV / Écran' },
    { value: 'photo', label: 'Appareil photo' },
    { value: 'accessoires', label: 'Accessoires' },
    { value: 'console', label: 'Console de jeux' },
    { value: 'autre', label: 'Autre' },
  ],
  mode: [
    { value: '', label: 'Toute la mode' },
    { value: 'homme', label: 'Vêtements homme' },
    { value: 'femme', label: 'Vêtements femme' },
    { value: 'enfant', label: 'Enfant' },
    { value: 'chaussures', label: 'Chaussures' },
    { value: 'sacs', label: 'Sacs' },
    { value: 'bijoux', label: 'Bijoux / Montres' },
    { value: 'autre', label: 'Autre' },
  ],
  maison: [
    { value: '', label: 'Tout maison & jardin' },
    { value: 'meubles', label: 'Meubles' },
    { value: 'electromenager', label: 'Électroménager' },
    { value: 'decoration', label: 'Décoration' },
    { value: 'jardinage', label: 'Jardinage' },
    { value: 'literie', label: 'Literie' },
    { value: 'cuisine', label: 'Cuisine / Vaisselle' },
    { value: 'autre', label: 'Autre' },
  ],
  animaux: [
    { value: '', label: 'Tous les animaux' },
    { value: 'chien', label: '🐕 Chien' },
    { value: 'chat', label: '🐈 Chat' },
    { value: 'oiseau', label: '🐦 Oiseau' },
    { value: 'poisson', label: '🐟 Poisson' },
    { value: 'lapin', label: '🐇 Lapin' },
    { value: 'reptile', label: '🦎 Reptile' },
    { value: 'vache', label: '🐄 Vache' },
    { value: 'chevre', label: '🐐 Chèvre' },
    { value: 'mouton', label: '🐑 Mouton' },
    { value: 'volaille', label: '🐓 Volaille / Poulet' },
    { value: 'cheval', label: '🐎 Cheval' },
    { value: 'cochon', label: '🐷 Cochon' },
    { value: 'autre', label: 'Autre' },
  ],
  agriculture: [
    { value: '', label: 'Toute l\'agriculture' },
    { value: 'semences', label: 'Semences / Plants' },
    { value: 'engrais', label: 'Engrais / Pesticides' },
    { value: 'outils', label: 'Outils agricoles' },
    { value: 'recolte', label: 'Récolte / Produits' },
    { value: 'betail', label: 'Bétail' },
    { value: 'irrigation', label: 'Irrigation' },
    { value: 'autre', label: 'Autre' },
  ],
  materiaux: [
    { value: '', label: 'Tous les matériaux' },
    { value: 'ciment', label: 'Ciment / Béton' },
    { value: 'fer', label: 'Fer / Acier' },
    { value: 'bois', label: 'Bois' },
    { value: 'peinture', label: 'Peinture' },
    { value: 'carrelage', label: 'Carrelage / Tuiles' },
    { value: 'plomberie', label: 'Plomberie' },
    { value: 'electricite', label: 'Électricité' },
    { value: 'autre', label: 'Autre' },
  ],
  sante: [
    { value: '', label: 'Tout santé & beauté' },
    { value: 'medicaments', label: 'Médicaments' },
    { value: 'cosmetiques', label: 'Cosmétiques' },
    { value: 'materiel-medical', label: 'Matériel médical' },
    { value: 'bien-etre', label: 'Bien-être' },
    { value: 'autre', label: 'Autre' },
  ],
  sport: [
    { value: '', label: 'Tout sport & loisirs' },
    { value: 'football', label: 'Football' },
    { value: 'fitness', label: 'Fitness / Musculation' },
    { value: 'velo', label: 'Vélo' },
    { value: 'natation', label: 'Natation' },
    { value: 'arts-martiaux', label: 'Arts martiaux' },
    { value: 'jeux', label: 'Jeux / Jouets' },
    { value: 'autre', label: 'Autre' },
  ],
  education: [
    { value: '', label: 'Tout éducation' },
    { value: 'livres', label: 'Livres / Manuels' },
    { value: 'cours', label: 'Cours particuliers' },
    { value: 'fournitures', label: 'Fournitures scolaires' },
    { value: 'formation', label: 'Formation / Certification' },
    { value: 'autre', label: 'Autre' },
  ],
  services: [
    { value: '', label: 'Tous les services' },
    { value: 'construction', label: 'Construction / BTP' },
    { value: 'menage', label: 'Ménage / Nettoyage' },
    { value: 'transport', label: 'Transport / Livraison' },
    { value: 'informatique', label: 'Informatique / Web' },
    { value: 'coiffure', label: 'Coiffure / Beauté' },
    { value: 'plomberie', label: 'Plomberie' },
    { value: 'electricite', label: 'Électricité' },
    { value: 'securite', label: 'Sécurité / Gardiennage' },
    { value: 'autre', label: 'Autre' },
  ],
}

export const MAIN_CATEGORIES = [
  { value: 'immo', label: '🏡 Immo', navbar: true },
  { value: 'voiture', label: '🚗 Autos', navbar: true },
  { value: 'moto', label: '🛵 Motos', navbar: true },
  { value: 'electronique', label: '📱 Tech', navbar: true },
  { value: 'mode', label: '👗 Mode', navbar: true },
  { value: 'agriculture', label: '🌾 Agri', navbar: true },
  { value: 'materiaux', label: '🧱 BTP', navbar: true },
  { value: 'sante', label: '💊 Santé', navbar: true },
  { value: 'sport', label: '⚽ Sport', navbar: true },
  { value: 'education', label: '📚 Éduc', navbar: true },
  { value: 'animaux', label: '🐄 Animaux', navbar: true },
  { value: 'services', label: '🏗️ Services', navbar: true },
]

// Pour le formulaire publier — catégories principales sans immo groupé
export const PUBLISH_CATEGORIES = [
  { value: 'immo-vente', label: '🏡 Immobilier Vente' },
  { value: 'immo-location', label: '🏢 Immobilier Location' },
  { value: 'immo-terrain', label: '🌿 Terrain' },
  { value: 'voiture', label: '🚗 Voitures' },
  { value: 'moto', label: '🛵 Motos' },
  { value: 'electronique', label: '📱 Électronique' },
  { value: 'mode', label: '👗 Mode et Beauté' },
  { value: 'maison', label: '🛋️ Maison et Jardin' },
  { value: 'emploi', label: '💼 Emploi' },
  { value: 'animaux', label: '🐄 Animaux' },
  { value: 'services', label: '🏗️ Services' },
  { value: 'agriculture', label: '🌾 Agriculture' },
  { value: 'materiaux', label: '🧱 Matériaux Construction' },
  { value: 'sante', label: '💊 Santé et Beauté' },
  { value: 'sport', label: '⚽ Sport et Loisirs' },
  { value: 'education', label: '📚 Éducation' },
]
